export const benchmarkInput = [
  {
    benchmarkInputSetups: [
      {
        benchmarkUnit: "V",
        benchmarkInputSetupName: "Negative Voltage",
        voltageType: "sweep",
        dataType: "float",
        decimalNumber: 2,
        exampleData: "-1.50",
        upperLimit: 0.0,
        lowerLimit: -3.0,
        stepIncresing: 0.5,
      },
      {
        benchmarkUnit: "V",
        benchmarkInputSetupName: "Positive Voltage",
        voltageType: "sweep",
        dataType: "float",
        decimalNumber: 2,
        exampleData: "1.50",
        upperLimit: 3.0,
        lowerLimit: 0.0,
        stepIncresing: 0.5,
      },
      {
        benchmarkUnit: "us",
        benchmarkInputSetupName: "Voltage Width/Duration",
        voltageType: "sweep",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "100",
        upperLimit: 1000, //1000us = 1ms
        lowerLimit: 10,
        stepIncresing: 100,
      },
      {
        benchmarkUnit: "V",
        benchmarkInputSetupName: "Voltage Step Resolution",
        voltageType: "sweep",
        dataType: "float",
        decimalNumber: 2,
        exampleData: "1.50",
        upperLimit: 10.0,
        lowerLimit: 1.0,
        stepIncresing: 0.5,
      },
      {
        benchmarkUnit: "number",
        benchmarkInputSetupName: "Sweep Cycle",
        voltageType: "sweep",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "1",
        upperLimit: 10,
        lowerLimit: 1,
        stepIncresing: 1,
      },
      {
        benchmarkUnit: "number",
        benchmarkInputSetupName: "Device Channel",
        voltageType: "sweep",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "1",
        upperLimit: 10,
        lowerLimit: 1,
        stepIncresing: 1,
      },
    ],
    active: true,
    benchmarkInputName: "Sweep IV curve Input",
    voltageType: "sweep",
    BenchmarkMethod: [],
  },
  {
    benchmarkInputSetups: [
      {
        benchmarkUnit: "V",
        benchmarkInputSetupName: "Negative Voltage",
        voltageType: "pulse",
        dataType: "float",
        decimalNumber: 2,
        exampleData: "-1.50",
        upperLimit: 0.0,
        lowerLimit: -3.0,
        stepIncresing: 0.5,
      },
      {
        benchmarkUnit: "V",
        benchmarkInputSetupName: "Positive Voltage",
        voltageType: "pulse",
        dataType: "float",
        decimalNumber: 2,
        exampleData: "1.50",
        upperLimit: 3.0,
        lowerLimit: 0.0,
        stepIncresing: 0.5,
      },
      {
        benchmarkUnit: "us",
        benchmarkInputSetupName: "Voltage Width/Duration",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "100",
        upperLimit: 1000, //1000us = 1ms
        lowerLimit: 10,
        stepIncresing: 100,
      },
      {
        benchmarkUnit: "V",
        benchmarkInputSetupName: "Voltage Step Resolution",
        voltageType: "pulse",
        dataType: "float",
        decimalNumber: 2,
        exampleData: "1.50",
        upperLimit: 10.0,
        lowerLimit: 1.0,
        stepIncresing: 0.5,
      },
      {
        benchmarkUnit: "us",
        benchmarkInputSetupName: "Interpulse Interval",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "100",
        upperLimit: 1000, //1000us = 1ms
        lowerLimit: 10,
        stepIncresing: 100,
      },
      {
        benchmarkUnit: "number",
        benchmarkInputSetupName: "Pulse IV Cycle",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "1",
        upperLimit: 10,
        lowerLimit: 1,
        stepIncresing: 1,
      },
      {
        benchmarkUnit: "number",
        benchmarkInputSetupName: "Device Channel",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "1",
        upperLimit: 10,
        lowerLimit: 1,
        stepIncresing: 1,
      },
    ],
    active: true,
    benchmarkInputName: "Pulse IV curve Input",
    voltageType: "pulse",
    BenchmarkMethod: [],
  },
  {
    benchmarkInputSetups: [
      {
        benchmarkUnit: "V",
        benchmarkInputSetupName: "Negative Voltage",
        voltageType: "pulse",
        dataType: "float",
        decimalNumber: 2,
        exampleData: "-1.50",
        upperLimit: 0.0,
        lowerLimit: -3.0,
        stepIncresing: 0.5,
      },
      {
        benchmarkUnit: "V",
        benchmarkInputSetupName: "Read Voltage",
        voltageType: "pulse",
        dataType: "float",
        decimalNumber: 2,
        exampleData: "1.50",
        upperLimit: 3.0,
        lowerLimit: 0.0,
        stepIncresing: 0.5,
      },
      {
        benchmarkUnit: "V",
        benchmarkInputSetupName: "Positive Voltage",
        voltageType: "pulse",
        dataType: "float",
        decimalNumber: 2,
        exampleData: "1.50",
        upperLimit: 3.0,
        lowerLimit: 0.0,
        stepIncresing: 0.5,
      },
      {
        benchmarkUnit: "us",
        benchmarkInputSetupName: "Negative Voltage Width/Duration",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "100",
        upperLimit: 1000, //1000us = 1ms
        lowerLimit: 10,
        stepIncresing: 100,
      },
      {
        benchmarkUnit: "us",
        benchmarkInputSetupName: "Positive Voltage Width/Duration",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "100",
        upperLimit: 1000, //1000us = 1ms
        lowerLimit: 10,
        stepIncresing: 100,
      },
      {
        benchmarkUnit: "second",
        benchmarkInputSetupName: "How long to measure in a single pulse",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "10",
        upperLimit: 100, //1000us = 1ms
        lowerLimit: 1,
        stepIncresing: 1,
      },
      {
        benchmarkUnit: "us",
        benchmarkInputSetupName: "Waiting time to test at every",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "100",
        upperLimit: 1000, //1000us = 1ms
        lowerLimit: 10,
        stepIncresing: 100,
      },
      {
        benchmarkUnit: "pulse number",
        benchmarkInputSetupName: "Programming Pulse",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "1",
        upperLimit: 100,
        lowerLimit: 1,
        stepIncresing: 1,
      },
      {
        benchmarkUnit: "number",
        benchmarkInputSetupName: "Programming Cycle Testing",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "1",
        upperLimit: 10,
        lowerLimit: 1,
        stepIncresing: 1,
      },
      {
        benchmarkUnit: "number",
        benchmarkInputSetupName: "Device Channel",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "1",
        upperLimit: 10,
        lowerLimit: 1,
        stepIncresing: 1,
      },
    ],
    active: true,
    benchmarkInputName: "Conductance vs PulseNumber Input",
    voltageType: "pulse",
    BenchmarkMethod: [],
  },
  {
    benchmarkInputSetups: [
      {
        benchmarkUnit: "V",
        benchmarkInputSetupName: "Negative Voltage",
        voltageType: "pulse",
        dataType: "float",
        decimalNumber: 2,
        exampleData: "-1.50",
        upperLimit: 0.0,
        lowerLimit: -3.0,
        stepIncresing: 0.5,
      },
      {
        benchmarkUnit: "V",
        benchmarkInputSetupName: "Read Voltage",
        voltageType: "pulse",
        dataType: "float",
        decimalNumber: 2,
        exampleData: "1.50",
        upperLimit: 3.0,
        lowerLimit: 0.0,
        stepIncresing: 0.5,
      },
      {
        benchmarkUnit: "V",
        benchmarkInputSetupName: "Positive Voltage",
        voltageType: "pulse",
        dataType: "float",
        decimalNumber: 2,
        exampleData: "1.50",
        upperLimit: 3.0,
        lowerLimit: 0.0,
        stepIncresing: 0.5,
      },
      {
        benchmarkUnit: "us",
        benchmarkInputSetupName: "Negative Voltage Width/Duration",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "100",
        upperLimit: 1000, //1000us = 1ms
        lowerLimit: 10,
        stepIncresing: 100,
      },
      {
        benchmarkUnit: "us",
        benchmarkInputSetupName: "Read Voltage Width/Duration",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "100",
        upperLimit: 1000, //1000us = 1ms
        lowerLimit: 10,
        stepIncresing: 100,
      },
      {
        benchmarkUnit: "us",
        benchmarkInputSetupName: "Positive Voltage Width/Duration",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "100",
        upperLimit: 1000, //1000us = 1ms
        lowerLimit: 10,
        stepIncresing: 100,
      },
      {
        benchmarkUnit: "us",
        benchmarkInputSetupName: "Interpulse Interval",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "100",
        upperLimit: 1000, //1000us = 1ms
        lowerLimit: 10,
        stepIncresing: 100,
      },
      {
        benchmarkUnit: "number",
        benchmarkInputSetupName: "Endurance Cycle Testing",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "1",
        upperLimit: 10,
        lowerLimit: 1,
        stepIncresing: 1,
      },
      {
        benchmarkUnit: "number",
        benchmarkInputSetupName: "Device Channel",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "1",
        upperLimit: 10,
        lowerLimit: 1,
        stepIncresing: 1,
      },
    ],
    active: true,
    benchmarkInputName: "Endurance Cycle Input",
    voltageType: "pulse",
    BenchmarkMethod: [],
  },
  {
    benchmarkInputSetups: [
      {
        benchmarkUnit: "V",
        benchmarkInputSetupName: "Negative Voltage",
        voltageType: "sweep",
        dataType: "float",
        decimalNumber: 2,
        exampleData: "-1.50",
        upperLimit: 0.0,
        lowerLimit: -3.0,
        stepIncresing: 0.5,
      },
      {
        benchmarkUnit: "V",
        benchmarkInputSetupName: "Read Voltage",
        voltageType: "sweep",
        dataType: "float",
        decimalNumber: 2,
        exampleData: "1.50",
        upperLimit: 3.0,
        lowerLimit: 0.0,
        stepIncresing: 0.5,
      },
      {
        benchmarkUnit: "V",
        benchmarkInputSetupName: "Positive Voltage",
        voltageType: "sweep",
        dataType: "float",
        decimalNumber: 2,
        exampleData: "1.50",
        upperLimit: 3.0,
        lowerLimit: 0.0,
        stepIncresing: 0.5,
      },
      {
        benchmarkUnit: "us",
        benchmarkInputSetupName: "Negative Voltage Width/Duration",
        voltageType: "sweep",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "100",
        upperLimit: 1000, //1000us = 1ms
        lowerLimit: 10,
        stepIncresing: 100,
      },
      {
        benchmarkUnit: "us",
        benchmarkInputSetupName:
          "Read Voltage Width/Duration\nHow long to measure",
        voltageType: "sweep",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "100",
        upperLimit: 1000, //1000us = 1ms
        lowerLimit: 10,
        stepIncresing: 100,
      },
      {
        benchmarkUnit: "us",
        benchmarkInputSetupName: "Positive Voltage Width/Duration",
        voltageType: "sweep",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "100",
        upperLimit: 1000, //1000us = 1ms
        lowerLimit: 10,
        stepIncresing: 100,
      },
      {
        benchmarkUnit: "us",
        benchmarkInputSetupName: "Interpulse Interval",
        voltageType: "sweep",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "100",
        upperLimit: 1000, //1000us = 1ms
        lowerLimit: 10,
        stepIncresing: 100,
      },
      {
        benchmarkUnit: "number",
        benchmarkInputSetupName: "Retention Time Cycle Testing",
        voltageType: "sweep",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "1",
        upperLimit: 10,
        lowerLimit: 1,
        stepIncresing: 1,
      },
      {
        benchmarkUnit: "number",
        benchmarkInputSetupName: "Device Channel",
        voltageType: "sweep",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "1",
        upperLimit: 10,
        lowerLimit: 1,
        stepIncresing: 1,
      },
    ],
    active: true,
    benchmarkInputName: "Sweep Retention Time Input",
    voltageType: "sweep",
    BenchmarkMethod: [],
  },
  {
    benchmarkInputSetups: [
      {
        benchmarkUnit: "V",
        benchmarkInputSetupName: "Negative Voltage",
        voltageType: "pulse",
        dataType: "float",
        decimalNumber: 2,
        exampleData: "-1.50",
        upperLimit: 0.0,
        lowerLimit: -3.0,
        stepIncresing: 0.5,
      },
      {
        benchmarkUnit: "V",
        benchmarkInputSetupName: "Read Voltage",
        voltageType: "pulse",
        dataType: "float",
        decimalNumber: 2,
        exampleData: "1.50",
        upperLimit: 3.0,
        lowerLimit: 0.0,
        stepIncresing: 0.5,
      },
      {
        benchmarkUnit: "V",
        benchmarkInputSetupName: "Positive Voltage",
        voltageType: "pulse",
        dataType: "float",
        decimalNumber: 2,
        exampleData: "1.50",
        upperLimit: 3.0,
        lowerLimit: 0.0,
        stepIncresing: 0.5,
      },
      {
        benchmarkUnit: "us",
        benchmarkInputSetupName: "Negative Voltage Width/Duration",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "100",
        upperLimit: 1000, //1000us = 1ms
        lowerLimit: 10,
        stepIncresing: 100,
      },
      {
        benchmarkUnit: "us",
        benchmarkInputSetupName: "Positive Voltage Width/Duration",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "100",
        upperLimit: 1000, //1000us = 1ms
        lowerLimit: 10,
        stepIncresing: 100,
      },
      {
        benchmarkUnit: "second",
        benchmarkInputSetupName: "How long to measure in a single pulse",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "10",
        upperLimit: 100, //1000us = 1ms
        lowerLimit: 1,
        stepIncresing: 1,
      },
      {
        benchmarkUnit: "number",
        benchmarkInputSetupName: "Pulse Cycle",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "1",
        upperLimit: 10,
        lowerLimit: 1,
        stepIncresing: 1,
      },
      {
        benchmarkUnit: "number",
        benchmarkInputSetupName: "Retention Time Cycle Testing",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "1",
        upperLimit: 10,
        lowerLimit: 1,
        stepIncresing: 1,
      },
      {
        benchmarkUnit: "number",
        benchmarkInputSetupName: "Device Channel",
        voltageType: "pulse",
        dataType: "Int",
        decimalNumber: 0,
        exampleData: "1",
        upperLimit: 10,
        lowerLimit: 1,
        stepIncresing: 1,
      },
    ],
    active: true,
    benchmarkInputName: "Pulse Retention Time Input",
    voltageType: "pulse",
    BenchmarkMethod: [],
  },
];
